// <auto-generated />
using System;
using Facebook.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Facebook.Migrations
{
    [DbContext(typeof(FacebookContext))]
    [Migration("20200519095641_Facebookvs1")]
    partial class Facebookvs1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Facebook.DTO.Image", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImageLink")
                        .HasMaxLength(50);

                    b.Property<int?>("UserId");

                    b.HasKey("ImageId");

                    b.HasIndex("UserId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("Facebook.DTO.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BackgroundPhotoImageId");

                    b.Property<DateTime>("BirthDate");

                    b.Property<string>("Email")
                        .HasMaxLength(30);

                    b.Property<string>("FirstName")
                        .HasMaxLength(20);

                    b.Property<string>("Gender")
                        .HasMaxLength(10);

                    b.Property<string>("LastName")
                        .HasMaxLength(20);

                    b.Property<string>("Password")
                        .HasMaxLength(30);

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15);

                    b.Property<int?>("ProfilePhotoImageId");

                    b.HasKey("UserId");

                    b.HasIndex("BackgroundPhotoImageId");

                    b.HasIndex("ProfilePhotoImageId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Facebook.DTO.Image", b =>
                {
                    b.HasOne("Facebook.DTO.User")
                        .WithMany("Images")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Facebook.DTO.User", b =>
                {
                    b.HasOne("Facebook.DTO.Image", "BackgroundPhoto")
                        .WithMany()
                        .HasForeignKey("BackgroundPhotoImageId");

                    b.HasOne("Facebook.DTO.Image", "ProfilePhoto")
                        .WithMany()
                        .HasForeignKey("ProfilePhotoImageId");
                });
#pragma warning restore 612, 618
        }
    }
}
